# Generated by Django 3.0.8 on 2021-11-30 02:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('queryid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('query_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='liked',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
